version: '3'

volumes:
    postgres_data:
        driver: local

services:
    mongodb:
        image: mongo:4.0.24
        container_name: mongodb

    iot-http:
        image: borokero/borokero-iot-http:0.0.1
        restart: always
        container_name: iot-http
        hostname: iot-http
        ports:
            - "127.0.0.1:3000:3000"
        environment:
            NODE_ENV: production
        # env_file: iot-http.env
        depends_on:
            - mongodb

    iot-mqtt:
        image: borokero/borokero-iot-mqtt:0.0.1
        restart: always
        container_name: iot-mqtt
        expose:
            - 1883
            - 8883
            - 8888
        environment:
            NODE_ENV: production
        # env_file: iot-mqtt.env
        depends_on:
            - mongodb

    postgres:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
    
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_SCHEMA: public
            DB_PASSWORD: password
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
            #JDBC_PARAMS: "ssl=true"
        ports:
            - 8080:8080
        depends_on:
            - postgres